# Project information
site_name: "VertDocs"

site_description: 'Vertcoin Documentation'
site_url: 'http://docs.vertcoin.org'
repo_url: 'https://github.com/VertDocs/VertDocs'

theme:
  name: 'material'

pages:
    - Home: index.md
    - Getting Started: getting-started.md
    - Wallets: 
        - Wallet Overview: Wallets/Wallet-Overview.md
        - Core Wallet: Wallets/Core-Wallet.md
        - Electrum Wallet: Wallets/Electrum.md
        - Vertwallet: Wallets/Vertwallet.md
        - Paper Wallets: Wallets/Paper-Wallets.md
        - Hardware Wallets: Wallets/Hardware-Wallets.md
    - Mining:
        - Getting Started with Mining: Mining/Getting-Started-With-Mining.md
        - P2pool Overview: Mining/P2pool-overview.md
        - NVidia Mining: Mining/Nvidia-Mining.md
        - AMD Mining: Mining/AMD-Mining.md
    - Full Nodes:
        - Raspberry Pi 4: FullNodes/raspberry-pi.md
    - Trading Vertcoin:
        - How to trade Vertcoin: TradingVertcoin/Where-to-trade-Vertcoin.md
    - Contributing:
        - How to contribute: Contributing/Contributing.md

   
extra_css:
  - 'stylesheets/extra.css'
  
extra:  
    
  social:
    - type: 'github'
      link: 'https://github.com/vertcoin-project'
    - type: 'twitter'
      link: 'https://twitter.com/vertcoin'
    - type: 'reddit'
      link: 'https://www.reddit.com/r/vertcoin/'
    - type: 'youtube'
      link: 'https://www.youtube.com/channel/UC7lBpTciARdSuRCQlFSe7Hw'
    - type: 'discord'
      link: 'https://discord.gg/vertcoin'
      
   
copyright: 'Copyright &copy; 2018-present Vertcoin'


markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
  
  
